### ISSUE TITLE
[Question] 单机单卡训练，报错，无法初始化梯度。

### ISSUE THREAD

**Issue by xkjcf** [baichuan-inc/Baichuan-7B#109]
### Required prerequisites

- [X] I have read the documentation <https://github.com/baichuan-inc/baichuan-7B/blob/HEAD/README.md>.
- [X] I have searched the [Issue Tracker](https://github.com/baichuan-inc/baichuan-7B/issues) and [Discussions](https://github.com/baichuan-inc/baichuan-7B/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/baichuan-inc/baichuan-7B/discussions/new).

### Questions

下载了model，创建了data_dir目录，创建了一个新的script/train2.sh脚本。
`
#!/bin/bash
deepspeed train.py \
--deepspeed \
--deepspeed_config config/deepspeed.json
`
运行该脚本，报如下的错误：
`
Traceback (most recent call last):
  File "/root/code/Baichuan-7B/train.py", line 138, in <module>
    model_engine = prepare_model()
  File "/root/code/Baichuan-7B/train.py", line 117, in prepare_model
    model_engine, _, _, _ = deepspeed.initialize(args=args,
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 308, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1173, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1409, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 468, in __init__
    self.initialize_gradient_partitioning_data_structures()
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 691, in initialize_gradient_partitioning_data_structures
    self.first_param_index_in_partition[i][partition_id] = self.get_first_param_index(
  File "/root/miniconda3/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 666, in get_first_param_index
    if partition_id in self.param_to_partition_ids[group_id][param_id]:
KeyError: 0
`

data_dir中的训练文档为普通的多行文本。

### Checklist

- [X] I have provided all relevant and necessary information above.
- [X] I have chosen a suitable title for this issue.

**Comment by DoliteMatheo** [comment]
同问，Python 3.9也不行，换了机器也不行。

**Comment by LiManshiang** [comment]
同问，遇到了相同的问题。
另一个问题时requirement 中版本有冲突
The conflict is caused by:
    The user requested torch==2.0.0
    deepspeed 0.9.2 depends on torch
    xformers 0.0.20 depends on torch==2.0.1

**Comment by xzhoubinx** [comment]
开stage-3就没问题了。

**Comment by Aurora-slz** [comment]
+1

**Comment by kztao** [comment]
同问

**Comment by hingkan** [comment]
> 同问，遇到了相同的问题。 另一个问题时requirement 中版本有冲突 The conflict is caused by: The user requested torch==2.0.0 deepspeed 0.9.2 depends on torch xformers 0.0.20 depends on torch==2.0.1

我在其他issue里也看到了，安装的也是torch==2.0.1，但仍然出现上面的问题。请问大家是如何解决的呢？

**Comment by yanglei627** [comment]
大佬们都是怎么解决的 求教

**Comment by xinruozhang575** [comment]
我也遇到了同样的问题，在deepspeed issues中有找到相关说明https://github.com/microsoft/DeepSpeed/issues/3234，ZeRO stage 3支持zero.init，stage 1和2不支持，我把deepspeed.json中stage改成3解决了这个问题

**Comment by Silentssss** [comment]
> 我也遇到了同样的问题，在deepspeed issues中有找到相关说明[https://github.com/microsoft/DeepSpeed/issues/3234，ZeRO](https://github.com/microsoft/DeepSpeed/issues/3234%EF%BC%8CZeRO) stage 3支持zero.init，stage 1和2不支持，我把deepspeed.json中stage改成3解决了这个问题

![image](https://github.com/baichuan-inc/Baichuan-7B/assets/108161275/00667787-3e62-4d38-a3cb-58028ab740ea)
按你的方法修改后有新的报错，你有遇到吗

**Comment by ucaslei** [comment]
> > 我也遇到了同样的问题，在deepspeed issues中有找到相关说明[https://github.com/microsoft/DeepSpeed/issues/3234，ZeRO](https://github.com/microsoft/DeepSpeed/issues/3234%EF%BC%8CZeRO) stage 3支持zero.init，stage 1和2不支持，我把deepspeed.json中stage改成3解决了这个问题
> 
> ![image](https://private-user-images.githubusercontent.com/108161275/294867193-00667787-3e62-4d38-a3cb-58028ab740ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjUxMjQsIm5iZiI6MTcyMjkyNDgyNCwicGF0aCI6Ii8xMDgxNjEyNzUvMjk0ODY3MTkzLTAwNjY3Nzg3LTNlNjItNGQzOC1hM2NiLTU4MDI4YWI3NDBlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwNjEzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzY5ZmVmZjExY2FhNGEyNDkyZTU5ZDAwMDY2ZDRiNzI1MjJmOTMwNzY3ODJjOGMwNWIwZjllOGQxZTJiOWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Rhvwc7t6R4x5Jq7dcZK8uVzgKRsBIYKvbXIljcrv5L0) 按你的方法修改后有新的报错，你有遇到吗

我也遇到这个问题了 有解决方法吗
