### ISSUE TITLE
[Question] 下载模型的时候报错 connection reset by pear

### ISSUE THREAD

**Issue by XCD4P** [baichuan-inc/baichuan-7B#60]
### Required prerequisites

- [X] I have read the documentation <https://github.com/baichuan-inc/baichuan-7B/blob/HEAD/README.md>.
- [X] I have searched the [Issue Tracker](https://github.com/baichuan-inc/baichuan-7B/issues) and [Discussions](https://github.com/baichuan-inc/baichuan-7B/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/baichuan-inc/baichuan-7B/discussions/new).

### Questions

from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("baichuan-inc/baichuan-7B", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("baichuan-inc/baichuan-7B", device_map="auto", trust_remote_code=True)
inputs = tokenizer('登鹳雀楼->王之涣\n夜雨寄北->', return_tensors='pt')
inputs = inputs.to('cuda:0')
pred = model.generate(**inputs, max_new_tokens=64,repetition_penalty=1.1)
print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))

运行上述代码，报错

Traceback (most recent call last):
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/connection.py", line 635, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 466, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 510, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/connection.py", line 635, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 466, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 510, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cuixin/baichuan-7B/inference.py", line 6, in <module>
    tokenizer = AutoTokenizer.from_pretrained("baichuan-inc/baichuan-7B",trust_remote_code=True)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 693, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1771, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1364, in hf_hub_download
    http_get(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 505, in http_get
    r = _request_wrapper(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 442, in _request_wrapper
    return http_backoff(
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 212, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/cuixin/anaconda3/envs/baichuan-7B/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### Checklist

- [X] I have provided all relevant and necessary information above.
- [X] I have chosen a suitable title for this issue.

**Comment by jiacheo** [comment]
这种是你的环境连huggingface网络不稳定
1. 写个while try catch，反复重试，直至成功
2. 手动下载（git lfs)，然后指定本地模型目录加载
